import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/common/Navbar/Navbar";


const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '600'],
    variable: '--font-poppins'
});

const pilatWide = localFont({
    src: [
        { path: "../../public/fonts/pilat-wide/PilatWide-Thin.woff2", weight: "100" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Light.woff2", weight: "300" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Regular.woff2", weight: "400" },
        { path: "../../public/fonts/pilat-wide/PilatWide-DemiBold.woff2", weight: "600" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Bold.woff2", weight: "700" },
        { path: "../../public/fonts/pilat-wide/PilatWide-Black.woff2", weight: "900" },
    ],
    variable: "--font-pilat",
});

const reyork = localFont({
    src: [
        {
            path: "../../public/fonts/reyork-fonts/reyork-regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/reyork-fonts/reyork-regular.otf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-reyork",
});

const dmSans = localFont({
    src: [
        {
            path: "../../public/fonts/dm-sans/DMSans-Medium.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/dm-sans/DMSans-Regular.ttf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-dmsans",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${reyork.variable} ${pilatWide.variable} ${poppins.variable} ${dmSans.variable}`}>
                <Navbar />
                {children}
            </body>
        </html >
    );
}
